### ISSUE TITLE
libdc1394 error: Failed to initialize libdc1394

### ISSUE THREAD

**Issue by naarkhoo** [bshaffer/faceswap-docker#1]
I am giving your repos. a try on Google cloud and the error is libdc1394 error: Failed to initialize libdc1394

**Comment by nikitalpopov** [comment]
The same error:
```bash
libdc1394 error: Failed to initialize libdc1394
Traceback (most recent call last):
  File "/usr/local/bin/faceswap.py", line 203, in <module>
    im1, landmarks1 = read_im_and_landmarks(sys.argv[1])
  File "/usr/local/bin/faceswap.py", line 173, in read_im_and_landmarks
    s = get_landmarks(im)
  File "/usr/local/bin/faceswap.py", line 96, in get_landmarks
    raise NoFaces
__main__.NoFaces
```
